version: 1.2
workflows:
  - name: run_flare
    subclass: WDL
    primaryDescriptorPath: /FLARE.wdl
    testParameterFiles:
      - /flare_test_data.json
  - name: plot_flare
    subclass: WDL
    primaryDescriptorPath: /plot_flare.wdl

